### ISSUE TITLE
Typo on the task for this project on the open Kanban board at KXStudio.

### ISSUE THREAD

**Issue by shivpalkang** [falkTX/kuriborosu#2]
Hi, 
  I didn't know where to report this, but the name of the task for this project on the open Kanban board at kxstudio site is wrong:
> https://board.kx.studio/public/task/13/f062a2b1cf34806109a3936a9373b8f044f0e0ab4ede4f1e2bf76195af27

It says `Kuroborosu` and should be `Kuriborosu`
Great idea for the tool by the way. Waiting for it materialize.

**Comment by falkTX** [comment]
Thanks for the attention.

I locked myself out of the board, but now got access again (manually editing the DB file hah...)

Anyway, fixed now.
